apiVersion: v1
kind: Secret
metadata:
  name: firstuser-password
type: Opaque
data:
  identity-firstuser-password: {{ include "common.secrets.passwords.manage" (dict "secret" "firstuser-password" "key" "identity-firstuser-password" "length" 16 "providedValues" (list "") "context" $) }}
