name: "compose: test opensearch"
on:
  push:
    branches:
      - "**"
jobs:
  test_core:
    uses: ./.github/workflows/template-deploy.yaml
    secrets: inherit
    with:
      compose_args: "-f docker-compose-core.yaml --profile opensearch"
      run_e2e_tests: false
      search_db: opensearch
