name: "Docker Compose | E2E Test - Setup"
on:
  push:
    branches:
      - main
      - 4-aa-migrate-docker-compose
    paths:
      - docker-compose/versions/**

jobs:
  test:
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Camunda 8.3 - Full
            camunda-version: "8.3"
            compose-args: "-f docker-compose.yaml -f docker-compose-web-modeler.yaml"
            e2e-test-enabled: true
          - name: Camunda 8.4 - Full
            camunda-version: "8.4"
            compose-args: "-f docker-compose.yaml -f docker-compose-web-modeler.yaml"
            e2e-test-enabled: true
          - name: Camunda 8.5 - Full
            camunda-version: "8.5"
            compose-args: "-f docker-compose.yaml -f docker-compose-web-modeler.yaml"
            e2e-test-enabled: true
          - name: Camunda 8.6 - Full
            camunda-version: "8.6"
            compose-args: "--profile full"
            e2e-test-enabled: true
    uses: ./.github/workflows/docker-compose-template-e2e-setup.yaml
    secrets: inherit
    with:
      camunda-version: ${{ matrix.camunda-version }}
      compose-args: ${{ matrix.compose-args }}
      e2e-test-enabled: ${{ matrix.e2e-test-enabled }}
